filter:
    excluded_paths:
        - 'l10n/*'
        - 'tests/'
        - 'vendor/*'

imports:
    - javascript
    - php

tools:
    external_code_coverage:
        timeout: 3600 # Timeout in seconds. 60 minutes
